kind: pipeline
name: wms-logging-starter

volumes:
  - name: m2-cache
    host:
      path: /tmp/m2-cache-new
  - name: docker
    host:
      path: /var/run/docker.sock

anchors:
  - &mvn-step
    image: ghcr.io/daymarket/maven:3.8.5-openjdk-17
    pull: always
    privileged: true
    volumes:
      - name: m2-cache
        path: /root/.m2
      - name: docker
        path: /var/run/docker.sock
    environment:
      SERVER_USERNAME:
        from_secret: nexus_maven_um_writer_username
      SERVER_PASSWORD:
        from_secret: nexus_maven_um_writer_password
      GIT_PUSH_SSH_KEY:
        from_secret: ghmachine_ssh_key

steps:
  - name: enforce-snapshot-version
    <<: *mvn-step
    commands:
      - mvn enforcer:enforce@snapshot-version
    when:
      branch:
        - feature/WMS-12478

  - name: prepare-deploy
    <<: *mvn-step
    commands:
      - mkdir ~/.ssh/
      - echo "$GIT_PUSH_SSH_KEY" > ~/.ssh/id_rsa
      - eval `ssh-agent -s`
      - chmod 400 ~/.ssh/id_rsa
      - ssh-add ~/.ssh/id_rsa
      - ssh-add -l
      - git config --global user.email "${DRONE_COMMIT_AUTHOR_EMAIL}"
      - git config --global user.name "${DRONE_COMMIT_AUTHOR}"
      - git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - mvn -B versions:use-releases -DprocessParent=true
      - mvn -B scm:checkin -Dmessage="[SKIP CI] Update dependency versions" -DpushChanges=false
      - mvn -B -DskipTests -Darguments=-DskipTests release:prepare
#      - git fetch origin development
#      - git checkout development
#      - git merge master --no-ff --no-edit -m "Merge branch 'master' into development [skip test]"
      - git push
    when:
      branch:
        - master
      event:
        - push

  - name: build-and-test
    <<: *mvn-step
    commands:
      - mvn package -U -B
    when:
      ref:
        - refs/heads/master
        - refs/pull/**

  - name: tests
    <<: *mvn-step
    commands:
      - mvn test -U -B
    when:
      ref:
        - refs/tags/*

  - name: deploy to nexus
    <<: *mvn-step
    commands:
      - mvn deploy -B -Dmaven.test.skip=true -Dmaven.install.skip=true
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        - push
        - tag
#
#  - name: telegram
#    image: appleboy/drone-telegram
#    failure: ignored
#    environment:
#      TELEGRAM_TOKEN:
#        from_secret: telegram_token
#      TELEGRAM_TO:
#        from_secret: telegram_to
#    when:
#      status:
#        - success
#        - failure
#      ref:
#        - refs/heads/master
#        - refs/tags/*
#    settings:
#      format: markdown
#      message: >
#        {{#success build.status}}
#        ⚙️ Status: build successful ✅
#        {{else}}
#        ⚙️ Status: build failed 🚨
#        {{/success}}
#        🔸 Repository: {{repo.owner}}/{{repo.name}}
#        ☘️ Branch: ** {{commit.branch}} **
#        📌 Commit: [{{commit.message}}]({{commit.link}})
#        🚀 Build URL: [build {{build.number}}]({{build.link}})
#        👨‍💻  Author:  [@{{commit.author}}](https://github.com/{{commit.author}})
